// dump-auxserver dumps auxserver.idx files
package main

import (
	"flag"
	"fmt"
	"log"
	"strings"

	"github.com/thkukuk/rpm2docserv/pkg/redirect"
)

var (
	indexPaths = flag.String("index",
		"/srv/docserv/auxserver.idx",
		"List of comma separated path to auxserver index files generated by rpm2docserv")
)

// use go build -ldflags "-X main.rpm2docservVersion=<version>" to set the version
var rpm2docservVersion = "HEAD"

func main() {
	flag.Parse()

	fmt.Printf("dump-auxserver loading index from %q\n", *indexPaths)

	splittedPaths := strings.Split(*indexPaths, ",")
	idx, err := redirect.IndexFromProto(splittedPaths)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Loaded %d manpage entries, %d products, %d languages, %d sections from index %q\n",
		len(idx.Entries), len(idx.ProductNames), len(idx.Langs), len(idx.Sections), *indexPaths)

	fmt.Printf("Entries: %q\n", idx.Entries)
	fmt.Printf("Product Names: %q\n", idx.ProductNames)
	fmt.Printf("Product Mapping: %q\n", idx.ProductMapping)
	fmt.Printf("Langs: %q\n", idx.Langs)
	fmt.Printf("Sections: %q\n", idx.Sections)
}
